services:
  - type: web
    name: mandaca-backend-staging
    runtime: docker
    dockerfilePath: ./Dockerfile
    branch: dev
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /docs
    envVars:
      - key: APP_ENV
        value: staging
      - key: APP_DEBUG
        value: "false"
