"""Corrigido nullable de avaliacoes

Revision ID: 17cec839c5ef
Revises: 4441e3369ffb
Create Date: 2026-04-07 17:29:46.771319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17cec839c5ef'
down_revision: Union[str, Sequence[str], None] = '4441e3369ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
