"""scrum214_unique_empresa_relatorio_ia

Revision ID: 1a08a2dc2532
Revises: 9f1d420a9524
Create Date: 2026-05-01 16:45:24.088346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a08a2dc2532'
down_revision: Union[str, Sequence[str], None] = '9f1d420a9524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_relatorios_ia_empresa', 'relatorios_ia', ['empresa_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_relatorios_ia_empresa', 'relatorios_ia', type_='unique')
    # ### end Alembic commands ###
