"""Retirado numero de mesas de reservas

Revision ID: 1d65c4e27110
Revises: cc35bffcf9a7
Create Date: 2026-06-19 16:26:23.244126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d65c4e27110'
down_revision: Union[str, Sequence[str], None] = 'cc35bffcf9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('horario_reserva', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('reservas', 'num_mesas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservas', sa.Column('num_mesas', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('reservas', 'horario_reserva')
    # ### end Alembic commands ###
