"""SCRUM87_add_lat_lng_to_empresas

Revision ID: 2bd14c84c3b0
Revises: scrum84_remove_transcricoes
Create Date: 2026-04-07 11:15:00.631265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd14c84c3b0'
down_revision: Union[str, Sequence[str], None] = 'scrum84_remove_transcricoes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('empresas', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'longitude')
    op.drop_column('empresas', 'latitude')
    # ### end Alembic commands ###
