"""Adicionado status para reservas

Revision ID: 415578617141
Revises: 20260526scrum195
Create Date: 2026-06-04 15:51:54.699072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415578617141'
down_revision: Union[str, Sequence[str], None] = '20260526scrum195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_reserva_enum = sa.Enum("aguardando", "aceito", name="status_reserva_enum")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_reserva_enum.create(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_chatbot_modulos_chatbot_ativo'), table_name='chatbot_modulos_conhecimento')
    op.drop_index(op.f('ix_chatbot_modulos_chatbot_topico'), table_name='chatbot_modulos_conhecimento')
    op.create_index(op.f('ix_chatbot_modulos_conhecimento_chatbot_id'), 'chatbot_modulos_conhecimento', ['chatbot_id'], unique=False)
    op.add_column("reservas",sa.Column("status",sa.Enum("aguardando", "aceito", name="status_reserva_enum"),nullable=False,server_default="aguardando",),)    
    op.alter_column("reservas", "status", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservas', 'status')
    status_reserva_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_chatbot_modulos_conhecimento_chatbot_id'), table_name='chatbot_modulos_conhecimento')
    op.create_index(op.f('ix_chatbot_modulos_chatbot_topico'), 'chatbot_modulos_conhecimento', ['chatbot_id', 'topico'], unique=False)
    op.create_index(op.f('ix_chatbot_modulos_chatbot_ativo'), 'chatbot_modulos_conhecimento', ['chatbot_id', 'ativo'], unique=False)
    # ### end Alembic commands ###
