"""SCRUM87_add_deleted_at_to_empresas

Revision ID: 4441e3369ffb
Revises: 2bd14c84c3b0
Create Date: 2026-04-07 11:47:32.552904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4441e3369ffb'
down_revision: Union[str, Sequence[str], None] = '2bd14c84c3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'deleted_at')
    # ### end Alembic commands ###
