"""scrum45_add_relatorios_ia_table

Revision ID: 678a7290ff34
Revises: 867035010774
Create Date: 2026-04-22 08:42:28.926287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678a7290ff34'
down_revision: Union[str, Sequence[str], None] = '867035010774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatorios_ia',
    sa.Column('id_relatorio', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('contexto_id', sa.UUID(), nullable=False),
    sa.Column('pontos_positivos_resumo', sa.Text(), nullable=False),
    sa.Column('pontos_positivos_detalhado', sa.Text(), nullable=False),
    sa.Column('melhorias_resumo', sa.Text(), nullable=False),
    sa.Column('melhorias_detalhado', sa.Text(), nullable=False),
    sa.Column('recomendacoes_resumo', sa.Text(), nullable=False),
    sa.Column('recomendacoes_detalhado', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contexto_id'], ['contextos_negocio.id_contexto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id_empresa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_relatorio')
    )
    op.create_index(op.f('ix_relatorios_ia_contexto_id'), 'relatorios_ia', ['contexto_id'], unique=False)
    op.create_index(op.f('ix_relatorios_ia_empresa_id'), 'relatorios_ia', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relatorios_ia_empresa_id'), table_name='relatorios_ia')
    op.drop_index(op.f('ix_relatorios_ia_contexto_id'), table_name='relatorios_ia')
    op.drop_table('relatorios_ia')
    # ### end Alembic commands ###
