"""Adicionado nova entidade de contexto

Revision ID: 867035010774
Revises: 8fde59d054d2
Create Date: 2026-04-21 19:10:14.771313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '867035010774'
down_revision: Union[str, Sequence[str], None] = '8fde59d054d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contextos_negocio',
    sa.Column('id_contexto', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('hash_contexto', sa.String(length=64), nullable=False),
    sa.Column('dados_contexto', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id_empresa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_contexto')
    )
    op.create_index(op.f('ix_contextos_negocio_empresa_id'), 'contextos_negocio', ['empresa_id'], unique=False)
    op.alter_column('notificacoes', 'lida',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notificacoes', 'data_criacao',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notificacoes', 'data_criacao',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('notificacoes', 'lida',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_contextos_negocio_empresa_id'), table_name='contextos_negocio')
    op.drop_table('contextos_negocio')
    # ### end Alembic commands ###
