"""Adicionado create_at de avaliacao

Revision ID: 8d2587d835ea
Revises: 678a7290ff34
Create Date: 2026-04-28 22:29:34.332629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2587d835ea'
down_revision: Union[str, Sequence[str], None] = '678a7290ff34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("avaliacoes",sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.text("now()"),),)
    op.create_index(op.f('ix_avaliacoes_created_at'), 'avaliacoes', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avaliacoes_created_at'), table_name='avaliacoes')
    op.drop_column('avaliacoes', 'created_at')
    # ### end Alembic commands ###
