"""Adicionado entidade de contato

Revision ID: 8e4811567c05
Revises: 20260506tutoriais
Create Date: 2026-05-12 21:13:35.050354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4811567c05'
down_revision: Union[str, Sequence[str], None] = '20260506tutoriais'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contatos',
    sa.Column('id_contato', sa.UUID(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_contato')
    )
    op.drop_index(op.f('ix_tutoriais_ativo'), table_name='tutoriais')
    op.drop_index(op.f('ix_tutoriais_categoria_ordem'), table_name='tutoriais')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tutoriais_categoria_ordem'), 'tutoriais', ['categoria', 'ordem'], unique=False)
    op.create_index(op.f('ix_tutoriais_ativo'), 'tutoriais', ['ativo'], unique=False)
    op.drop_table('contatos')
    # ### end Alembic commands ###
