"""Correção de referencia entre as tabelas

Revision ID: 8f801e6a3f3c
Revises: a8775e0c9d95
Create Date: 2026-03-27 20:56:32.146873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f801e6a3f3c'
down_revision: Union[str, Sequence[str], None] = 'a8775e0c9d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('empresas_usuario_id_key'), 'empresas', type_='unique')
    op.create_index(op.f('ix_empresas_usuario_id'), 'empresas', ['usuario_id'], unique=True)
    op.drop_constraint(op.f('empresas_usuario_id_fkey'), 'empresas', type_='foreignkey')
    op.create_foreign_key(None, 'empresas', 'usuarios', ['usuario_id'], ['id_usuario'], ondelete='CASCADE')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.drop_constraint(op.f('usuarios_empresa_id_fkey'), 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'empresa_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('empresa_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('usuarios_empresa_id_fkey'), 'usuarios', 'empresas', ['empresa_id'], ['id_empresa'], ondelete='SET NULL')
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.create_foreign_key(op.f('empresas_usuario_id_fkey'), 'empresas', 'usuarios', ['usuario_id'], ['id_usuario'])
    op.drop_index(op.f('ix_empresas_usuario_id'), table_name='empresas')
    op.create_unique_constraint(op.f('empresas_usuario_id_key'), 'empresas', ['usuario_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
