"""scrum49_add_chat_messages_table

Revision ID: 8fde59d054d2
Revises: f2bc2c1e8eb6
Create Date: 2026-04-13 08:05:47.445972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8fde59d054d2'
down_revision: Union[str, Sequence[str], None] = 'f2bc2c1e8eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens_chat',
    sa.Column('id_mensagem', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('conteudo_usuario', sa.Text(), nullable=False),
    sa.Column('conteudo_assistente', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id_empresa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_mensagem')
    )
    op.create_index(op.f('ix_mensagens_chat_empresa_id'), 'mensagens_chat', ['empresa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_chat_empresa_id'), table_name='mensagens_chat')
    op.drop_table('mensagens_chat')
    # ### end Alembic commands ###
