"""Adicionado o restante das tabelas e dos relacionamentos

Revision ID: a8775e0c9d95
Revises: 460ed2200fa0
Create Date: 2026-03-27 18:39:05.663443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8775e0c9d95'
down_revision: Union[str, Sequence[str], None] = '460ed2200fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id_empresa', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('historia', sa.String(length=500), nullable=True),
    sa.Column('hora_abrir', sa.Time(), nullable=True),
    sa.Column('hora_fechar', sa.Time(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_empresa'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('avaliacoes',
    sa.Column('id_avaliacao', sa.UUID(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=True),
    sa.Column('tipo_avaliacao', sa.Enum('POSITIVA', 'NEGATIVA', 'NEUTRA', 'SUGESTAO', 'DUVIDA', name='tipo_avaliacao_enum'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id_empresa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_avaliacao')
    )
    op.create_index(op.f('ix_avaliacoes_empresa_id'), 'avaliacoes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_avaliacoes_usuario_id'), 'avaliacoes', ['usuario_id'], unique=False)
    op.create_table('cardapios',
    sa.Column('id_cardapio', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('historia', sa.String(length=500), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.Enum('ENTRADA', 'PRATO_PRINCIPAL', 'SOBREMESA', 'BEBIDA', 'LANCHE', name='categoria_cardapio_enum'), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id_empresa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cardapio')
    )
    op.create_index(op.f('ix_cardapios_empresa_id'), 'cardapios', ['empresa_id'], unique=False)
    op.create_table('fotos',
    sa.Column('id_foto', sa.UUID(), nullable=False),
    sa.Column('url_foto_empresa', sa.String(length=255), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id_empresa'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_index(op.f('ix_fotos_empresa_id'), 'fotos', ['empresa_id'], unique=False)
    op.create_table('reservas',
    sa.Column('id_reserva', sa.UUID(), nullable=False),
    sa.Column('num_mesas', sa.Integer(), nullable=False),
    sa.Column('num_pessoas', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(length=120), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id_empresa'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    op.create_index(op.f('ix_reservas_empresa_id'), 'reservas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_reservas_usuario_id'), 'reservas', ['usuario_id'], unique=False)
    op.create_foreign_key(None, 'usuarios', 'empresas', ['empresa_id'], ['id_empresa'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_reservas_usuario_id'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_empresa_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_fotos_empresa_id'), table_name='fotos')
    op.drop_table('fotos')
    op.drop_index(op.f('ix_cardapios_empresa_id'), table_name='cardapios')
    op.drop_table('cardapios')
    op.drop_index(op.f('ix_avaliacoes_usuario_id'), table_name='avaliacoes')
    op.drop_index(op.f('ix_avaliacoes_empresa_id'), table_name='avaliacoes')
    op.drop_table('avaliacoes')
    op.drop_table('empresas')
    # ### end Alembic commands ###
