"""scrum141_add_reservation_messages_table

Revision ID: cc35bffcf9a7
Revises: 20260609scrum193
Create Date: 2026-06-10 20:38:32.378696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc35bffcf9a7'
down_revision: Union[str, Sequence[str], None] = '20260609scrum193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

tipo_remetente_enum = sa.Enum("turista", "empreendedor", name="tipo_remetente_enum")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens_reserva',
    sa.Column('id_mensagem', sa.UUID(), nullable=False),
    sa.Column('reserva_id', sa.UUID(), nullable=False),
    sa.Column('remetente_id', sa.UUID(), nullable=False),
    sa.Column('tipo_remetente', tipo_remetente_enum, nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['remetente_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id_reserva'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_mensagem')
    )
    op.create_index(op.f('ix_mensagens_reserva_criado_em'), 'mensagens_reserva', ['criado_em'], unique=False)
    op.create_index(op.f('ix_mensagens_reserva_reserva_id'), 'mensagens_reserva', ['reserva_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_reserva_reserva_id'), table_name='mensagens_reserva')
    op.drop_index(op.f('ix_mensagens_reserva_criado_em'), table_name='mensagens_reserva')
    op.drop_table('mensagens_reserva')
    tipo_remetente_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
