"""scrum251_add_notas_conversa_to_contextos_negocio

Revision ID: e0457fdbd5b7
Revises: 415578617141
Create Date: 2026-06-07 23:10:28.800398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0457fdbd5b7'
down_revision: Union[str, Sequence[str], None] = '415578617141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contextos_negocio', sa.Column('notas_conversa', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contextos_negocio', 'notas_conversa')
    # ### end Alembic commands ###
