"""Adicionado fotos a entidade de cardapios

Revision ID: ea6b8f4e6c3b
Revises: 8e4811567c05
Create Date: 2026-05-22 16:21:06.420998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6b8f4e6c3b'
down_revision: Union[str, Sequence[str], None] = '8e4811567c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardapios', sa.Column('url_foto_item', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardapios', 'url_foto_item')
    # ### end Alembic commands ###
